language: node_js
node_js:
  - "12"
  - "14"
before_script:
  - npm run build
  - npm run build-test
  - npm run lint
  - npm run type-check
script:
  - npm run test-server
  - npm run test-browser-sauce
branches:
  only:
    - master
